// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwrwxofreukdgxiqfzea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3cnd4b2ZyZXVrZGd4aXFmemVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MjU5NzQsImV4cCI6MjA2NjAwMTk3NH0.uh0udpVAyhITRlRyrMkVIjw4s0e-ciGEY7fceEoQCPE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);